spring:
    datasource:
        url: jdbc:mysql://localhost:3306/bookstore?useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    application:
        name: bookstore
    jpa:
        show-sql: true
        properties:

            hibernate:
              format_sql: true

    profiles:
        active: prod
app:
    message: "default profile"
key:
    message: "miracle"
server:
    port: 8080

logging:
    level:
        org:
            springframework:
                web: DEBUG
            hibernate: ERROR
            com.bookapp01: INFO
            com.bookapp01.service: DEBUG

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always



