apiVersion: v1
kind: Pod
metadata:
  name: bookapp-pod
spec:
  containers:
    - name: app
      command: ["/bin/sh", "-c", "printenv"]
      image: bookapp:latest
      envFrom:
        - configMapRef:
            name: bookapp-config