apiVersion: v1
kind: Pod
metadata:
  name: bookapp-pod
spec:
  containers:
    - name: app
      command: ["/bin/sh", "-c", "printenv"]
      image: bookapp:latest
      env:
        - name: logging_mode
          valueFrom:
            configMapKeyRef:
              name: bookapp-config
              key: log_level