apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-app
spec:
  selector:
    matchLabels:
      app: book-app
  replicas: 2
  template:
    metadata:
      labels:
        app: book-app
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: product
        image: rahul471/k8s-ingress-product
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bookapp-service
spec:
  selector:
    app: bookapp
  ports:
  - port: 80
    targetPort: 80