apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - name: demo
    image: rgupta00/util
    args:
    - "sleep"
    - "3600"
---
apiVersion: v1
kind: Service
metadata:
  name: empapp-svc
spec:
  type: ClusterIP
  selector:
    app: empapp-service
  ports:
  - port: 8080
    targetPort: 8080
