apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - name: demo
    image: rahul471/bookapp:1.1
    args:
    - "sleep"
    - "3600"
---
apiVersion: v1
kind: Service
metadata:
  name: bookapp-svc
spec:
  type: ClusterIP
  selector:
    app: bookapp-service
  ports:
  - port: 8080
    targetPort: 8080
