apiVersion: v1
kind: Service
metadata:
  name: empapp-svc
spec:
  type: NodePort
  selector:
    app: empapp-service
  ports:
  - port: 8080 #port that we want to expose for pod
    targetPort: 8080 #port inside container
    nodePort: 30001
