spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: currency-conversion
server:
  port: 8100
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"  # Expose all endpoints for Prometheus
  endpoint:
    prometheus:
      enabled: true  # Enable Prometheus metrics
    metrics:
      enabled: true
    refresh:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  logging:
    pattern:
      level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/

