spring:
  cloud:
    config:
      server:
        git:
          uri: file:///C:/configfiles
          clone-on-start: true
          default-label: master
  application:
    name:
      configserver
management:
  endpoints:
    web:
      exposure:
        include: health,refresh,env
server:
  port: 8888