apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
spec:
  selector:
    matchLabels:
      app: bookapp
  replicas: 3
  template:
    metadata:
      name: bookapp
      labels:
        app: bookapp
    spec:
      containers:
      - name: bookapp
        image: rahul471/bookapp:1.1
