apiVersion: apps/v1
kind: Deployment
metadata:
  name: empapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empapp
  template:
    metadata:
      labels:
        app: empapp
    spec:
      containers:
        - name: empapp
          image: 396608804235.dkr.ecr.ap-south-1.amazonaws.com/rahul471/eks-exam:1.1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: empapp-service
spec:
  selector:
    app: empapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

